### ISSUE TITLE
Readme Grammer issue

### ISSUE THREAD

**Issue by oddnoob** [cakeslob/RRW_LAB#2]
In the Readme there is a Grammer mistake where they're is a "he" used instead of a "the" which should been already fixed because improper Grammer is an issue

From the readme:
The board exists for the single purpose to promote the Remora project, with **_he_** design goals to be an expensive, hard to make, and inaccessible while still retaining the core features.

**Comment by cakeslob** [comment]
thank you concerned user for the heads up, but Kelsey Grammer is not affiliated with the project as of right now. I see the typo you are referring to thought. If you would like to submit a pull request with the corrected changes to the grammar that would be great.
